INTERFACES = [
    {"code": "DASHBOARD", "libelle": "Dashboard", "route": "/dashboard", "icon": "LayoutDashboard", "module": "DASHBOARD", "ordre": 10},
    {"code": "SEC_UTILISATEURS", "libelle": "Utilisateurs", "route": "/utilisateurs", "icon": "Users", "module": "SECURITE", "ordre": 20},
    {"code": "SEC_ROLES", "libelle": "Rôles", "route": "/roles", "icon": "Shield", "module": "SECURITE", "ordre": 21},
    {"code": "SEC_PERMISSIONS", "libelle": "Permissions", "route": "/permissions", "icon": "Key", "module": "SECURITE", "ordre": 22},
    {"code": "SEC_SESSIONS", "libelle": "Sessions", "route": "/sessions", "icon": "MonitorSmartphone", "module": "SECURITE", "ordre": 23},
    {"code": "SEC_JOURNAL_AUDIT", "libelle": "Journal audit", "route": "/journal-audit", "icon": "ClipboardList", "module": "SECURITE", "ordre": 24},
    {"code": "ORGANISATION", "libelle": "Organisation", "route": "/organisation", "icon": "Building2", "module": "ORGANISATION", "ordre": 30},
    {"code": "ORG_SOCIETES", "libelle": "Sociétés", "route": "/societes", "icon": "Building2", "module": "ORGANISATION", "ordre": 31},
    {"code": "ORG_SITES", "libelle": "Sites", "route": "/sites", "icon": "MapPin", "module": "ORGANISATION", "ordre": 32},
    {"code": "ORG_SECTEURS", "libelle": "Secteurs", "route": "/secteurs", "icon": "Grid3x3", "module": "ORGANISATION", "ordre": 33},
    {"code": "ORG_UNITES", "libelle": "Unités", "route": "/unites", "icon": "Factory", "module": "ORGANISATION", "ordre": 34},
    {"code": "ORG_SPECIALITES", "libelle": "Spécialités", "route": "/specialites", "icon": "Wrench", "module": "ORGANISATION", "ordre": 35},
    {"code": "ORG_EQUIPES", "libelle": "Équipes", "route": "/equipes", "icon": "UsersRound", "module": "ORGANISATION", "ordre": 36},
    {"code": "ORG_APPARTENANCES", "libelle": "Appartenances", "route": "/appartenances", "icon": "Link2", "module": "ORGANISATION", "ordre": 37},
    {"code": "ACTIFS_LISTE", "libelle": "Actifs", "route": "/actifs", "icon": "Package", "module": "ACTIFS", "ordre": 40},
    {"code": "ACTIFS_DASHBOARD", "libelle": "Dashboard actifs", "route": "/actifs/dashboard", "icon": "BarChart2", "module": "ACTIFS", "ordre": 41},
    {"code": "ACTIFS_ARBORESCENCE", "libelle": "Arborescence actifs", "route": "/actifs/arborescence", "icon": "FolderTree", "module": "ACTIFS", "ordre": 42},
    {"code": "ACTIFS_RACINES", "libelle": "Actifs racines", "route": "/actifs-racines", "icon": "GitBranch", "module": "ACTIFS", "ordre": 43},
    {"code": "ACTIFS_UNITE", "libelle": "Actifs par unité", "route": "/actifs/unite", "icon": "Factory", "module": "ACTIFS", "ordre": 44},
    {"code": "MAGASIN_CATALOGUE", "libelle": "Catalogue pièces", "route": "/magasin", "icon": "Package2", "module": "MAGASIN", "ordre": 50},
    {"code": "MAGASIN_DASHBOARD", "libelle": "Dashboard magasin", "route": "/magasin/dashboard", "icon": "Store", "module": "MAGASIN", "ordre": 51},
    {"code": "MAGASIN_SORTIE", "libelle": "Sortie magasin", "route": "/magasin/sortie", "icon": "ArrowDownToLine", "module": "MAGASIN", "ordre": 52},
    {"code": "SOUS_TRAITANTS_LISTE", "libelle": "Sous-traitants", "route": "/soustraitants", "icon": "Hammer", "module": "SOUS_TRAITANTS", "ordre": 60},
    {"code": "SOUS_TRAITANTS_DASHBOARD", "libelle": "Dashboard sous-traitants", "route": "/soustraitants/dashboard", "icon": "BarChart2", "module": "SOUS_TRAITANTS", "ordre": 61},
    {"code": "ORDRES_DEMANDES", "libelle": "Demandes (DI)", "route": "/ordres/demandes", "icon": "FileText", "module": "ORDRES", "ordre": 70},
    {"code": "ORDRES_DASHBOARD_OT", "libelle": "Dashboard OT", "route": "/ordres/ots/dashboard", "icon": "BarChart2", "module": "ORDRES", "ordre": 71},
    {"code": "ORDRES_OTS", "libelle": "Ordres (OT)", "route": "/ordres/ots", "icon": "ClipboardCheck", "module": "ORDRES", "ordre": 72},
    {"code": "ORDRES_DECLARER", "libelle": "Déclarer panne", "route": "/ordres/declarer", "icon": "AlertTriangle", "module": "ORDRES", "ordre": 73},
    {"code": "ORDRES_GESTION", "libelle": "Gestion OT", "route": "/ordres/gestion", "icon": "Settings2", "module": "ORDRES", "ordre": 74},
    {"code": "ORDRES_VALIDATION", "libelle": "Valider interventions", "route": "/ordres/validation", "icon": "CheckCircle2", "module": "ORDRES", "ordre": 75},
    {"code": "PARAMETRAGE", "libelle": "Paramétrage", "route": "/parametrage", "icon": "Settings2", "module": "PARAMETRAGE", "ordre": 80},
    {"code": "PARAMETRAGE_BACKUP", "libelle": "Sauvegarde", "route": "/parametrage/backup", "icon": "DatabaseBackup", "module": "PARAMETRAGE", "ordre": 90},
]

PERMISSIONS = [
    ("ADMIN_UTILISATEUR_CREATE", "ADMIN", "CREATE", "Utilisateur"),
    ("ADMIN_UTILISATEUR_READ", "ADMIN", "READ", "Utilisateur"),
    ("ADMIN_UTILISATEUR_UPDATE", "ADMIN", "UPDATE", "Utilisateur"),
    ("ADMIN_UTILISATEUR_DELETE", "ADMIN", "DELETE", "Utilisateur"),
    ("ADMIN_ROLE_CREATE", "ADMIN", "CREATE", "Role"),
    ("ADMIN_ROLE_READ", "ADMIN", "READ", "Role"),
    ("ADMIN_ROLE_UPDATE", "ADMIN", "UPDATE", "Role"),
    ("ADMIN_PERMISSION_READ", "ADMIN", "READ", "Permission"),
    ("ADMIN_PERMISSION_UPDATE", "ADMIN", "UPDATE", "Permission"),
    ("ADMIN_ORGANISATION_CREATE", "ADMIN", "CREATE", "Organisation"),
    ("ADMIN_ORGANISATION_UPDATE", "ADMIN", "UPDATE", "Organisation"),
    ("ADMIN_ORGANISATION_READ", "ADMIN", "READ", "Organisation"),
    ("ADMIN_EQUIPE_CREATE", "ADMIN", "CREATE", "Equipe"),
    ("ADMIN_EQUIPE_UPDATE", "ADMIN", "UPDATE", "Equipe"),
    ("ADMIN_EQUIPE_READ", "ADMIN", "READ", "Equipe"),
    ("ADMIN_JOURNAL_READ", "ADMIN", "READ", "JournalAudit"),
    ("ACTIF_CREATE", "ACTIFS", "CREATE", "Actif"),
    ("ACTIF_READ", "ACTIFS", "READ", "Actif"),
    ("ACTIF_UPDATE", "ACTIFS", "UPDATE", "Actif"),
    ("ACTIF_DELETE", "ACTIFS", "DELETE", "Actif"),
    ("ACTIF_CHANGER_STATUT", "ACTIFS", "UPDATE", "ActifStatut"),
    ("ACTIF_HISTORIQUE_READ", "ACTIFS", "READ", "HistoriqueStatutActif"),
    ("DI_CREATE", "INTERVENTIONS", "CREATE", "DemandeIntervention"),
    ("DI_READ", "INTERVENTIONS", "READ", "DemandeIntervention"),
    ("DI_UPDATE", "INTERVENTIONS", "UPDATE", "DemandeIntervention"),
    ("DI_VALIDER", "INTERVENTIONS", "VALIDER", "DemandeIntervention"),
    ("DI_REJETER", "INTERVENTIONS", "UPDATE", "DemandeIntervention"),
    ("OT_CREATE", "INTERVENTIONS", "CREATE", "OrdreTravail"),
    ("OT_READ", "INTERVENTIONS", "READ", "OrdreTravail"),
    ("OT_UPDATE", "INTERVENTIONS", "UPDATE", "OrdreTravail"),
    ("OT_AFFECTER_EQUIPE", "INTERVENTIONS", "UPDATE", "AffectationEquipe"),
    ("OT_AFFECTER_SOUSTRAIT", "INTERVENTIONS", "UPDATE", "AffectationSousTraitant"),
    ("OT_SAISIR_COMPTE_RENDU", "INTERVENTIONS", "UPDATE", "CompteRenduOT"),
    ("OT_CLOTURER", "INTERVENTIONS", "CLOTURER", "OrdreTravail"),
    ("OT_VALIDER_CLOTURE", "INTERVENTIONS", "VALIDER", "OrdreTravail"),
    ("OT_REJETER_CONFIRMATION", "INTERVENTIONS", "UPDATE", "OrdreTravail"),
    ("STOCK_PIECE_CREATE", "MAGASIN", "CREATE", "Piece"),
    ("STOCK_PIECE_READ", "MAGASIN", "READ", "Piece"),
    ("STOCK_PIECE_UPDATE", "MAGASIN", "UPDATE", "Piece"),
    ("STOCK_SORTIE", "MAGASIN", "CREATE", "MouvementStockSortie"),
    ("STOCK_ENTREE", "MAGASIN", "CREATE", "MouvementStockEntree"),
    ("STOCK_MOUVEMENT_READ", "MAGASIN", "READ", "MouvementStock"),
    ("ST_CREATE", "SOUS_TRAITANCE", "CREATE", "SousTraitant"),
    ("ST_READ", "SOUS_TRAITANCE", "READ", "SousTraitant"),
    ("ST_UPDATE", "SOUS_TRAITANCE", "UPDATE", "SousTraitant"),
    ("ST_SUSPENDRE", "SOUS_TRAITANCE", "UPDATE", "SousTraitantStatut"),
    ("KPI_READ", "REPORTING", "READ", "KPI"),
    ("KPI_TABLEAU_BORD_READ", "REPORTING", "READ", "TableauBord"),
    ("KPI_RAPPORT_EXPORT", "REPORTING", "READ", "Rapport"),
    ("KPI_COUT_READ", "REPORTING", "READ", "CoutMaintenance"),
    ("KPI_BUDGET_READ", "REPORTING", "READ", "Budget"),
    ("NOTIF_READ", "NOTIFICATIONS", "READ", "Notification"),
    ("NOTIF_REGLE_CREATE", "NOTIFICATIONS", "CREATE", "RegleNotification"),
    ("NOTIF_REGLE_UPDATE", "NOTIFICATIONS", "UPDATE", "RegleNotification"),
]

INTERFACE_PERMISSIONS = {
    "DASHBOARD": ["KPI_TABLEAU_BORD_READ", "KPI_READ", "NOTIF_READ"],
    "SEC_UTILISATEURS": ["ADMIN_UTILISATEUR_CREATE", "ADMIN_UTILISATEUR_READ", "ADMIN_UTILISATEUR_UPDATE", "ADMIN_UTILISATEUR_DELETE"],
    "SEC_ROLES": ["ADMIN_ROLE_CREATE", "ADMIN_ROLE_READ", "ADMIN_ROLE_UPDATE"],
    "SEC_PERMISSIONS": ["ADMIN_PERMISSION_READ", "ADMIN_PERMISSION_UPDATE"],
    "SEC_SESSIONS": ["ADMIN_UTILISATEUR_READ"],
    "SEC_JOURNAL_AUDIT": ["ADMIN_JOURNAL_READ"],
    "ORGANISATION": ["ADMIN_ORGANISATION_READ"],
    "ORG_SOCIETES": ["ADMIN_ORGANISATION_READ", "ADMIN_ORGANISATION_CREATE", "ADMIN_ORGANISATION_UPDATE"],
    "ORG_SITES": ["ADMIN_ORGANISATION_READ", "ADMIN_ORGANISATION_CREATE", "ADMIN_ORGANISATION_UPDATE"],
    "ORG_SECTEURS": ["ADMIN_ORGANISATION_READ", "ADMIN_ORGANISATION_CREATE", "ADMIN_ORGANISATION_UPDATE"],
    "ORG_UNITES": ["ADMIN_ORGANISATION_READ", "ADMIN_ORGANISATION_CREATE", "ADMIN_ORGANISATION_UPDATE"],
    "ORG_SPECIALITES": ["ADMIN_ORGANISATION_READ", "ADMIN_ORGANISATION_CREATE", "ADMIN_ORGANISATION_UPDATE"],
    "ORG_EQUIPES": ["ADMIN_EQUIPE_CREATE", "ADMIN_EQUIPE_READ", "ADMIN_EQUIPE_UPDATE"],
    "ORG_APPARTENANCES": ["ADMIN_ORGANISATION_READ", "ADMIN_ORGANISATION_CREATE", "ADMIN_ORGANISATION_UPDATE"],
    "ACTIFS_LISTE": ["ACTIF_CREATE", "ACTIF_READ", "ACTIF_UPDATE", "ACTIF_DELETE", "ACTIF_CHANGER_STATUT"],
    "ACTIFS_DASHBOARD": ["ACTIF_READ", "ACTIF_HISTORIQUE_READ", "KPI_READ", "KPI_TABLEAU_BORD_READ"],
    "ACTIFS_ARBORESCENCE": ["ACTIF_READ"],
    "ACTIFS_RACINES": ["ACTIF_READ"],
    "ACTIFS_UNITE": ["ACTIF_READ"],
    "MAGASIN_CATALOGUE": ["STOCK_PIECE_CREATE", "STOCK_PIECE_READ", "STOCK_PIECE_UPDATE", "STOCK_MOUVEMENT_READ"],
    "MAGASIN_DASHBOARD": ["STOCK_PIECE_READ", "STOCK_MOUVEMENT_READ", "KPI_READ"],
    "MAGASIN_SORTIE": ["STOCK_SORTIE", "STOCK_ENTREE"],
    "SOUS_TRAITANTS_LISTE": ["ST_CREATE", "ST_READ", "ST_UPDATE", "ST_SUSPENDRE"],
    "SOUS_TRAITANTS_DASHBOARD": ["ST_READ", "KPI_READ", "KPI_TABLEAU_BORD_READ"],
    "ORDRES_DEMANDES": ["DI_CREATE", "DI_READ", "DI_UPDATE", "DI_VALIDER", "DI_REJETER"],
    "ORDRES_DASHBOARD_OT": ["OT_READ", "KPI_READ", "KPI_TABLEAU_BORD_READ"],
    "ORDRES_OTS": ["OT_CREATE", "OT_READ", "OT_UPDATE", "OT_AFFECTER_EQUIPE", "OT_AFFECTER_SOUSTRAIT", "OT_SAISIR_COMPTE_RENDU", "OT_CLOTURER"],
    "ORDRES_DECLARER": ["DI_CREATE"],
    "ORDRES_GESTION": ["OT_CREATE", "OT_READ", "OT_UPDATE", "OT_AFFECTER_EQUIPE", "OT_AFFECTER_SOUSTRAIT", "OT_SAISIR_COMPTE_RENDU", "OT_CLOTURER", "DI_READ", "DI_VALIDER", "DI_REJETER"],
    "ORDRES_VALIDATION": ["OT_VALIDER_CLOTURE", "OT_REJETER_CONFIRMATION"],
    "PARAMETRAGE": ["ADMIN_PERMISSION_READ", "ADMIN_PERMISSION_UPDATE", "ADMIN_ROLE_READ", "ADMIN_ROLE_UPDATE"],
    "PARAMETRAGE_BACKUP": ["ADMIN_PERMISSION_READ"],
}
