# Generated by Django 5.2 on 2026-04-10 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0002_alter_societe_raisonsociale_and_more'),
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseRacine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('mecanique', 'Mécanique'), ('electrique', 'Électrique'), ('humain', 'Humain'), ('externe', 'Externe'), ('autre', 'Autre')], max_length=15)),
                ('description', models.TextField()),
                ('dateIdentification', models.DateField()),
            ],
            options={
                'verbose_name': 'Cause racine',
                'ordering': ['-dateIdentification'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentaire', models.TextField()),
                ('estInterne', models.BooleanField(default=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commentaire OT',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeOrdreTravail', models.CharField(max_length=15)),
                ('priorite', models.CharField(max_length=10)),
                ('delaiAffectationMin', models.IntegerField()),
                ('delaiResolutionMin', models.IntegerField()),
                ('estActif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration SLA',
            },
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('dateSignalement', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('urgence', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=15)),
                ('dateValidation', models.DateTimeField(blank=True, null=True)),
                ('motifRejet', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'ordering': ['-dateSignalement'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancienStatut', models.CharField(max_length=25)),
                ('nouveauStatut', models.CharField(max_length=25)),
                ('dateChangement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historique statut OT',
                'ordering': ['-dateChangement'],
            },
        ),
        migrations.CreateModel(
            name='MembreIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('minutesTravailles', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Membre intervention',
                'ordering': ['-dateDebut'],
            },
        ),
        migrations.CreateModel(
            name='OrdreTravail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('correctif', 'Correctif'), ('preventif', 'Préventif'), ('amelioration', 'Amélioration')], default='correctif', max_length=15)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('DEPANNE', 'Dépanné'), ('EN_ATTENTE_CORRECTION', 'En attente correction'), ('EN_VALIDATION', 'En validation'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=25)),
                ('estSousTraite', models.BooleanField(default=False)),
                ('estBloquant', models.BooleanField(default=False)),
                ('echeanceSLA', models.DateTimeField(blank=True, null=True)),
                ('dureeEstimeeMin', models.IntegerField(blank=True, null=True)),
                ('dureeReelleMin', models.IntegerField(blank=True, null=True)),
                ('coutMainOeuvre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coutSousTraitance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dateCloture', models.DateTimeField(blank=True, null=True)),
                ('typeCloture', models.CharField(blank=True, choices=[('corrige', 'Corrigé définitivement'), ('depanne', 'Dépanné temporairement'), ('annule', 'Annulé')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ordre de travail',
                'verbose_name_plural': 'Ordres de travail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeDI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomFichier', models.CharField(max_length=255)),
                ('typeFichier', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('dateTeleversement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce jointe DI',
                'ordering': ['-dateTeleversement'],
            },
        ),
        migrations.CreateModel(
            name='PieceUtiliseeOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12)),
                ('prixUnitaireCapture', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dateUtilisation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce utilisée OT',
                'ordering': ['-dateUtilisation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviTemps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heureDebut', models.DateTimeField()),
                ('heureFin', models.DateTimeField(blank=True, null=True)),
                ('minutesTravailles', models.IntegerField(default=0)),
                ('descriptionTravail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Suivi temps',
                'ordering': ['-heureDebut'],
            },
        ),
        migrations.CreateModel(
            name='AffectationEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=15)),
                ('coutPrestation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evaluationSousTraitant', models.IntegerField(blank=True, null=True)),
                ('idChefTechnicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_chef', to='securite.utilisateur')),
                ('idEquipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='organisation.equipe')),
            ],
            options={
                'verbose_name': 'Affectation équipe',
                'ordering': ['-dateDebut'],
            },
        ),
    ]
