# Generated by Django 5.2 on 2026-04-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actifs', '0002_actif_idparent'),
        ('magasin', '0001_initial'),
        ('ordres', '0001_initial'),
        ('organisation', '0002_alter_societe_raisonsociale_and_more'),
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
        ('soustraitants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationequipe',
            name='idSousTraitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='soustraitants.soustraitant'),
        ),
        migrations.AddField(
            model_name='causeracine',
            name='idUtilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causes_racine', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='commentaireot',
            name='idUtilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_ot', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='configurationsla',
            name='idSite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations_sla', to='organisation.site'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='idActif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='actifs.actif'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='idUtilisateurSignalement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_signalee', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='idUtilisateurValidation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='historiquestatutot',
            name='idUtilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_statut_ot', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='membreintervention',
            name='idAffectationEquipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='ordres.affectationequipe'),
        ),
        migrations.AddField(
            model_name='membreintervention',
            name='idUtilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='idActif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_travail', to='actifs.actif'),
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='idDemandeIntervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_travail', to='ordres.demandeintervention'),
        ),
        migrations.AddField(
            model_name='historiquestatutot',
            name='idOrdreTravail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_statut', to='ordres.ordretravail'),
        ),
        migrations.AddField(
            model_name='commentaireot',
            name='idOrdreTravail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ordres.ordretravail'),
        ),
        migrations.AddField(
            model_name='causeracine',
            name='idOrdreTravail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_racine', to='ordres.ordretravail'),
        ),
        migrations.AddField(
            model_name='affectationequipe',
            name='idOrdreTravail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='ordres.ordretravail'),
        ),
        migrations.AddField(
            model_name='piecejointedi',
            name='idDemandeIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='ordres.demandeintervention'),
        ),
        migrations.AddField(
            model_name='pieceutiliseeot',
            name='idMouvementStock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations_ot', to='magasin.mouvementstock'),
        ),
        migrations.AddField(
            model_name='pieceutiliseeot',
            name='idOrdreTravail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_utilisees', to='ordres.ordretravail'),
        ),
        migrations.AddField(
            model_name='pieceutiliseeot',
            name='idPiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_ot', to='magasin.piece'),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='idAffectationEquipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_temps', to='ordres.affectationequipe'),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='idOrdreTravail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_temps', to='ordres.ordretravail'),
        ),
        migrations.AddField(
            model_name='suivitemps',
            name='idUtilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_temps', to='securite.utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationsla',
            unique_together={('idSite', 'typeOrdreTravail', 'priorite')},
        ),
    ]
