# Generated by Django 5.2 on 2026-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretravail',
            name='isvalidee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordretravail',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('DEPANNE', 'Dépanné'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=25),
        ),
    ]
