# Generated by Django 5.2 on 2026-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0003_ordretravail_isvalidee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretravail',
            name='motifValidation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordretravail',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('DEPANNE', 'Dépanné'), ('EN_VALIDATION', 'En validation'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=25),
        ),
    ]
