# Generated by Django 5.2 on 2026-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0004_ordretravail_motifvalidation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordretravail',
            name='motifValidation',
        ),
        migrations.AlterField(
            model_name='ordretravail',
            name='statut',
            field=models.CharField(choices=[('REJETE', 'Rejeté'), ('EN_COURS', 'En cours'), ('DEPANNE', 'Dépanné'), ('CLOTURE', 'Clôturé')], default='EN_COURS', max_length=25),
        ),
    ]
