# Generated by Django 5.2 on 2026-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0005_remove_ordretravail_motifvalidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeintervention',
            name='isvalidee',
            field=models.BooleanField(default=False),
        ),
    ]
