# Generated by Django 5.2 on 2026-04-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0006_demandeintervention_isvalidee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordretravail',
            old_name='isvalidee',
            new_name='isencoure',
        ),
    ]
