# Generated by Django 5.2 on 2026-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0007_rename_isvalidee_ordretravail_isencoure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordretravail',
            old_name='isencoure',
            new_name='isvalidee',
        ),
        migrations.RemoveField(
            model_name='demandeintervention',
            name='isvalidee',
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='isencours',
            field=models.BooleanField(default=True),
        ),
    ]
