# Generated by Django 5.2 on 2026-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0008_rename_isencoure_ordretravail_isvalidee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordretravail',
            name='isvalidee',
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='isvalide',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='affectationequipe',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('rejeter', 'Rejeté')], default='en_attente', max_length=15),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='urgence',
            field=models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordretravail',
            name='priorite',
            field=models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], max_length=10),
        ),
    ]
