# Generated by Django 5.2 on 2026-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0009_remove_ordretravail_isvalidee_ordretravail_isvalide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeintervention',
            name='titre',
            field=models.CharField(blank=True),
        ),
    ]
