# Generated by Django 5.2 on 2026-05-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0010_demandeintervention_titre'),
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretravail',
            name='idUtilisateurCreateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_crees', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='idUtilisateurValidation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_valides', to='securite.utilisateur'),
        ),
    ]
