# Generated by Django 5.2 on 2026-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0011_ordretravail_idutilisateurcreateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeintervention',
            name='dateDernierRejet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeintervention',
            name='rejetCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demandeintervention',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('rejetee_apres_validation', 'Rejetée après validation')], default='en_attente', max_length=30),
        ),
    ]
