# Generated by Django 5.2 on 2026-05-05 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actifs', '0002_actif_idparent'),
        ('ordres', '0012_demandeintervention_datedernierrejet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActifCorrigeOT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('dateCorrection', models.DateTimeField(auto_now_add=True)),
                ('idActif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_ot', to='actifs.actif')),
                ('idOrdreTravail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs_corriges', to='ordres.ordretravail')),
            ],
            options={
                'verbose_name': 'Actif corrigé (OT)',
                'verbose_name_plural': 'Actifs corrigés (OT)',
                'ordering': ['-dateCorrection'],
                'unique_together': {('idOrdreTravail', 'idActif')},
            },
        ),
    ]
