# Generated by Django 5.2 on 2026-05-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0013_actifcorrigeot'),
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretravail',
            name='dateRejetOperateur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='idUtilisateurRejetOperateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_rejetes', to='securite.utilisateur'),
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='motifRejetOperateur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordretravail',
            name='rejetOperateur',
            field=models.BooleanField(default=False),
        ),
    ]
