# Generated by Django 5.2 on 2026-04-10 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0002_alter_societe_raisonsociale_and_more'),
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousTraitant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raisonSociale', models.CharField(max_length=200, unique=True)),
                ('ICE', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, default='')),
                ('contactPrincipalNom', models.CharField(blank=True, default='', max_length=100)),
                ('contactPrincipalTel', models.CharField(blank=True, default='', max_length=30)),
                ('contactPrincipalEmail', models.EmailField(max_length=150)),
                ('contactTechniqueNom', models.CharField(blank=True, default='', max_length=100)),
                ('contactTechniqueTel', models.CharField(blank=True, default='', max_length=30)),
                ('contactTechniqueEmail', models.EmailField(blank=True, max_length=150, null=True)),
                ('numeroContrat', models.CharField(blank=True, max_length=100, null=True)),
                ('tarifHoraireNormal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifHoraireSemaine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habilitations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('estActif', models.BooleanField(default=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('idUtilisateurCreateur', models.ForeignKey(db_column='id_utilisateur_createur', on_delete=django.db.models.deletion.PROTECT, related_name='sous_traitants_crees', to='securite.utilisateur')),
            ],
            options={
                'verbose_name': 'Sous-traitant',
                'verbose_name_plural': 'Sous-traitants',
                'db_table': 'sous_traitant',
                'ordering': ['raisonSociale'],
            },
        ),
        migrations.CreateModel(
            name='SousTraitantSpecialite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateAttribution', models.DateField(auto_now_add=True)),
                ('idSousTraitant', models.ForeignKey(db_column='id_sous_traitant', on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='soustraitants.soustraitant')),
                ('idSpecialite', models.ForeignKey(db_column='id_specialite', on_delete=django.db.models.deletion.CASCADE, related_name='sous_traitants', to='organisation.specialite')),
            ],
            options={
                'verbose_name': 'Spécialité sous-traitant',
                'verbose_name_plural': 'Spécialités sous-traitant',
                'db_table': 'sous_traitant_specialite',
                'constraints': [models.UniqueConstraint(fields=('idSousTraitant', 'idSpecialite'), name='unique_sous_traitant_specialite')],
                'unique_together': {('idSousTraitant', 'idSpecialite')},
            },
        ),
    ]
