# Generated by Django 5.2 on 2026-04-08 10:40

import django.utils.timezone
from django.db import migrations, models


def lowercase_statut(apps, schema_editor):
    """Convert ACTIF/INACTIF/SUSPENDU to actif/inactif/suspendu."""
    SousTraitant = apps.get_model('soustraitant', 'SousTraitant')
    for st in SousTraitant.objects.all():
        st.statut = st.statut.lower()
        st.save(update_fields=['statut'])


class Migration(migrations.Migration):

    dependencies = [
        ('soustraitant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustraitant',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='estActif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='contactPrincipalNom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='contactPrincipalTel',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='contactTechniqueNom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='contactTechniqueTel',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.RunPython(lowercase_statut, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='soustraitant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10),
        ),
        migrations.RenameField(
            model_name='soustraitantspecialite',
            old_name='dateAjout',
            new_name='dateAttribution',
        ),
        migrations.AlterField(
            model_name='soustraitantspecialite',
            name='dateAttribution',
            field=models.DateField(auto_now_add=True),
        ),
    ]
