# Generated by Django 5.2 on 2026-04-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soustraitant', '0002_audit_phase5_corrections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soustraitant',
            old_name='siret',
            new_name='ICE',
        ),
    ]
