# Generated by Django 5.2 on 2026-04-02 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('ressource', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('niveau', models.IntegerField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='SessionActive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('adresse_ip', models.GenericIPAddressField()),
                ('est_active', models.BooleanField(default=True)),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='securite.utilisateur')),
            ],
            options={
                'db_table': 'session_active',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('type_entite', models.CharField(max_length=100)),
                ('id_entite', models.UUIDField(blank=True, null=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='securite.utilisateur')),
            ],
            options={
                'db_table': 'journal_audit',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permission', models.ForeignKey(db_column='id_permission', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='securite.permission')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='securite.role')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('id_role', 'id_permission')},
            },
        ),
        migrations.CreateModel(
            name='UtilisateurRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='securite.role')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='securite.utilisateur')),
            ],
            options={
                'db_table': 'utilisateur_role',
                'unique_together': {('id_utilisateur', 'id_role')},
            },
        ),
    ]
