# Generated by Django 5.2 on 2026-03-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionactive',
            name='token',
        ),
    ]
