# Generated by Django 5.2 on 2026-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('id_role', 'id_permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='utilisateurrole',
            constraint=models.UniqueConstraint(fields=('id_utilisateur', 'id_role'), name='unique_user_role'),
        ),
    ]
