# Generated by Django 5.2 on 2026-05-07 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('module', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'interface_app',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='RoleInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interface', models.ForeignKey(db_column='id_interface', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='securite.interfaceapp')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='securite.role')),
            ],
            options={
                'db_table': 'role_interface',
                'constraints': [models.UniqueConstraint(fields=('id_role', 'id_interface'), name='unique_role_interface')],
                'unique_together': {('id_role', 'id_interface')},
            },
        ),
    ]
