# Generated by Django 5.2 on 2026-04-02 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Maroc', max_length=100)),
                ('estActif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site',
                'ordering': ['societe', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('raisonSociale', models.CharField(max_length=200)),
                ('estActif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['raisonSociale'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('estActif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
                ('estActif', models.BooleanField(default=True)),
                ('chefEquipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_chef', to='securite.utilisateur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='organisation.site')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='organisation.specialite')),
            ],
            options={
                'verbose_name': 'Équipe',
                'ordering': ['site', 'libelle'],
                'unique_together': {('site', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('estActif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='organisation.site')),
            ],
            options={
                'verbose_name': 'Secteur',
                'ordering': ['site', 'libelle'],
                'unique_together': {('site', 'code')},
            },
        ),
        migrations.AddField(
            model_name='site',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organisation.societe'),
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('estProductive', models.BooleanField(default=True)),
                ('estActif', models.BooleanField(default=True)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='organisation.secteur')),
            ],
            options={
                'verbose_name': 'Unité',
                'ordering': ['secteur', 'libelle'],
                'unique_together': {('secteur', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EquipeUtilisateur',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveauRole', models.CharField(choices=[('CHEF', 'Chef'), ('MEMBRE', 'Membre'), ('REMPLACANT', 'Remplaçant')], default='MEMBRE', max_length=20)),
                ('dateAdhesion', models.DateField(auto_now_add=True)),
                ('estActif', models.BooleanField(default=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organisation.equipe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_membre', to='securite.utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'ordering': ['equipe', 'niveauRole'],
                'unique_together': {('equipe', 'utilisateur')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('societe', 'code')},
        ),
        migrations.CreateModel(
            name='AppartenanceOrganisationnelle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estPrincipale', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances', to='securite.utilisateur')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.secteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.site')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.societe')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.unite')),
            ],
            options={
                'verbose_name': 'Appartenance organisationnelle',
                'constraints': [models.UniqueConstraint(condition=models.Q(('estPrincipale', True)), fields=('utilisateur',), name='unique_appartenance_principale')],
            },
        ),
    ]
