# Generated by Django 5.2 on 2026-03-31 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('securite', '0002_remove_sessionactive_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenanceorganisationnelle',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances', to='securite.utilisateur'),
        ),
        migrations.AlterField(
            model_name='equipeutilisateur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_membre', to='securite.utilisateur'),
        ),
    ]
