# Generated by Django 5.2 on 2026-03-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_appartenanceorganisationnelle_utilisateur_and_more'),
        ('securite', '0002_remove_sessionactive_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='chefEquipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_chef', to='securite.utilisateur'),
        ),
    ]
