# Generated by Django 5.2 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_societe_raisonsociale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartenanceorganisationnelle',
            name='unite',
        ),
        migrations.AddField(
            model_name='appartenanceorganisationnelle',
            name='unites',
            field=models.ManyToManyField(blank=True, related_name='appartenances_unites', to='organisation.unite'),
        ),
    ]
