# Generated by Django 5.2 on 2026-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_alter_equipe_chefequipe'),
        ('securite', '0003_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='raisonSociale',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='equipe',
            constraint=models.UniqueConstraint(fields=('site', 'specialite', 'libelle'), name='unique_equipe_site_specialite_libelle'),
        ),
        migrations.AddConstraint(
            model_name='equipeutilisateur',
            constraint=models.UniqueConstraint(condition=models.Q(('estActif', True)), fields=('utilisateur',), name='unique_utilisateur_equipe_active'),
        ),
        migrations.AddConstraint(
            model_name='equipeutilisateur',
            constraint=models.UniqueConstraint(fields=('equipe', 'utilisateur'), name='unique_equipe_utilisateur'),
        ),
    ]
