# Generated by Django 5.2 on 2026-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_alter_societe_raisonsociale_and_more'),
        ('securite', '0003_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipeutilisateur',
            name='unique_utilisateur_equipe_active',
        ),
        migrations.AddConstraint(
            model_name='equipeutilisateur',
            constraint=models.UniqueConstraint(condition=models.Q(('estActif', True)), fields=('utilisateur',), name='unique_utilisateur_equipe_active'),
        ),
    ]
