# Generated by Django 5.2 on 2026-03-30 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        (('securite', '0001_initial')),
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('equipement', 'Équipement'), ('infrastructure', 'Infrastructure'), ('vehicule', 'Véhicule'), ('autre', 'Autre')], default='equipement', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_panne', 'En panne'), ('en_maintenance', 'En maintenance'), ('retire', 'Retiré')], default='actif', max_length=20)),
                ('dateAcquisition', models.DateField(blank=True, null=True)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fabricant', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('numSerie', models.CharField(blank=True, max_length=100)),
                ('estActif', models.BooleanField(default=True)),
                ('idSite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actifs', to='organisation.site')),
                ('idUnite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actifs', to='organisation.unite')),
            ],
            options={
                'verbose_name': 'Actif',
                'verbose_name_plural': 'Actifs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancienStatut', models.CharField(max_length=20)),
                ('nouveauStatut', models.CharField(max_length=20)),
                ('dateChangement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True)),
                ('idActif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_statut', to='actifs.actif')),
                ('modifiePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_statut', to='securite.utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-dateChangement'],
            },
        ),
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('planifiee', 'Planifiée'), ('panne', 'Panne'), ('maintenance', 'Maintenance')], default='panne', max_length=20)),
                ('estTerminee', models.BooleanField(default=False)),
                ('idActif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='actifs.actif')),
            ],
            options={
                'verbose_name': 'Indisponibilité',
                'verbose_name_plural': 'Indisponibilités',
                'ordering': ['-dateDebut'],
            },
        ),
        migrations.CreateModel(
            name='Remplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateRemplacement', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('actifOriginal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements_sortants', to='actifs.actif')),
                ('actifRemplacant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacements_entrants', to='actifs.actif')),
                ('effectuePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements_effectues', to='securite.utilisateur')),
            ],
            options={
                'verbose_name': 'Remplacement',
                'verbose_name_plural': 'Remplacements',
                'ordering': ['-dateRemplacement'],
            },
        ),
    ]
