# Generated by Django 5.2 on 2026-05-11 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actifs', '0002_actif_idparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'actif",
                'verbose_name_plural': "Types d'actifs",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterField(
            model_name='actif',
            name='type',
            field=models.CharField(default='equipement', max_length=20),
        ),
    ]
