# Generated by Django 5.2 on 2026-03-26 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codeActif', models.CharField(max_length=20, unique=True, verbose_name='Code actif')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('type', models.CharField(choices=[('MECANIQUE', 'Mécanique'), ('ELECTRIQUE', 'Électrique'), ('HYDRAULIQUE', 'Hydraulique'), ('PNEUMATIQUE', 'Pneumatique'), ('AUTOMATISME', 'Automatisme'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type')),
                ('criticite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('ELEVEE', 'Élevée'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], max_length=10, verbose_name='Criticité')),
                ('statut', models.CharField(choices=[('EN_SERVICE', 'En service'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service'), ('EN_VEILLE', 'En veille')], default='EN_SERVICE', max_length=20, verbose_name='Statut')),
                ('numeroSerie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de série')),
                ('fabricant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricant')),
                ('modele', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('idParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='actif.actif', verbose_name='Actif parent')),
                ('idUnite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actifs', to='organisation.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Actif',
                'verbose_name_plural': 'Actifs',
                'db_table': 'actif',
                'ordering': ['codeActif'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutActif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancienStatut', models.CharField(choices=[('EN_SERVICE', 'En service'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service'), ('EN_VEILLE', 'En veille')], max_length=20, verbose_name='Ancien statut')),
                ('nouveauStatut', models.CharField(choices=[('EN_SERVICE', 'En service'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service'), ('EN_VEILLE', 'En veille')], max_length=20, verbose_name='Nouveau statut')),
                ('dateChangement', models.DateTimeField(verbose_name='Date du changement')),
                ('idActif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='actif.actif', verbose_name='Actif')),
                ('idUtilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_statut_actif', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique statut actif',
                'verbose_name_plural': 'Historiques statuts actifs',
                'db_table': 'historique_statut_actif',
                'ordering': ['-dateChangement'],
            },
        ),
    ]
