# Generated by Django 5.2 on 2026-04-04 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securite', '0002_rolepermission_unique_role_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('unite', models.CharField(default='piece', max_length=20)),
                ('emplacement', models.CharField(blank=True, help_text='Ex: A1-E3-N2', max_length=100)),
                ('quantiteStock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('seuilMinimum', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('prixUnitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('referenceConstructeur', models.CharField(blank=True, max_length=100)),
                ('dateDerniereEntree', models.DateTimeField(blank=True, null=True)),
                ('estActif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typeMouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stockAvant', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stockApres', models.DecimalField(decimal_places=3, max_digits=12)),
                ('idOrdreTravail', models.CharField(blank=True, max_length=100, null=True)),
                ('dateHeure', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('idUtilisateurMagasinier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_magasinier', to='securite.utilisateur')),
                ('idUtilisateurTechnicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_technicien', to='securite.utilisateur')),
                ('idPiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='magasin.piece')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-dateHeure'],
            },
        ),
    ]
